[package]
name = "rust_euler"
version = "0.1.0"
authors = ["Mike Meehan <mjmeehan@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3"
num = "0.2"

[lib]
name = "euler"
path = "src/lib/euler.rs"
